---
abstract: 'Generation of the static files of DuckDuckGo and its microsites.'
author:
  - 'Torsten Raudssus <torsten@raudss.us>'
build_requires:
  Test::EOL: '0'
  Test::LoadAllModules: '0.021'
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.027, CPAN::Meta::Converter version 2.143240'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DDG-Publisher
requires:
  CSS::Packer: '1.002001'
  Class::Load: '0.20'
  Config::INI: '0.019'
  DDP: '0'
  Dist::Zilla::Plugin::TravisCI: '0.003'
  File::Find: '0'
  File::Path: '0'
  File::ShareDir::ProjectDistDir: v0.3.2
  HTML::Packer: '1.004001'
  IO::All: '0.46'
  IPC::Run: '0'
  JSON: '2.57'
  JavaScript::Minifier::XS: '0'
  JavaScript::Packer: '1.006003'
  JavaScript::Value::Escape: '0'
  Locale::Simple: '0.008'
  Markdent: '0.24'
  MooX: '0.101'
  MooX::Options: '3.71'
  Path::Class: '0.26'
  String::ProgressBar: '0.03'
  Text::Trim: '0'
  Text::Xslate: '1.5017'
resources:
  homepage: https://github.com/duckduckgo/duckduckgo-publisher
  repository: https://github.com/duckduckgo/duckduckgo-publisher.git
version: '1042'
